# Generated by Django 3.2.13 on 2022-05-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='gender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='week1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='week2',
            field=models.IntegerField(),
        ),
    ]
